"""add nutrition constraints

Revision ID: 107e3c7fd825
Revises: b0eca8ed4f6e
Create Date: 2026-08-21 15:39:23.198087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107e3c7fd825'
down_revision: Union[str, Sequence[str], None] = 'b0eca8ed4f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_constraints',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('constraint_type', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_key', sa.String(length=120), nullable=False),
    sa.Column('operator', sa.String(length=24), nullable=False),
    sa.Column('value_min', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('value_max', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=24), nullable=True),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_date IS NULL OR end_date IS NULL OR end_date >= start_date', name='ck_nutrition_constraints_date_range_valid'),
    sa.CheckConstraint('value_max IS NULL OR value_max >= 0', name='ck_nutrition_constraints_value_max_nonnegative'),
    sa.CheckConstraint('value_min IS NULL OR value_max IS NULL OR value_max >= value_min', name='ck_nutrition_constraints_value_range_valid'),
    sa.CheckConstraint('value_min IS NULL OR value_min >= 0', name='ck_nutrition_constraints_value_min_nonnegative'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nutrition_constraints_person_target', 'nutrition_constraints', ['person_id', 'target_type', 'target_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nutrition_constraints_person_target', table_name='nutrition_constraints')
    op.drop_table('nutrition_constraints')
    # ### end Alembic commands ###
