"""add person profile and anthropometric measurements

Revision ID: 674a00880ad1
Revises: ea93f75a076f
Create Date: 2026-08-21 15:07:13.200247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674a00880ad1'
down_revision: Union[str, Sequence[str], None] = 'ea93f75a076f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anthropometric_measurements',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('source_device', sa.String(length=120), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value > 0', name='ck_anthropometric_measurements_value_positive'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anthropometric_person_metric_measured_at', 'anthropometric_measurements', ['person_id', 'metric', 'measured_at'], unique=False)
    op.create_table('person_profiles',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('sex_for_energy_calculation', sa.String(length=16), nullable=True),
    sa.Column('measurement_system', sa.String(length=16), nullable=False),
    sa.Column('energy_unit', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_profiles')
    op.drop_index('ix_anthropometric_person_metric_measured_at', table_name='anthropometric_measurements')
    op.drop_table('anthropometric_measurements')
    # ### end Alembic commands ###
