"""add nutrition goals

Revision ID: b0eca8ed4f6e
Revises: 674a00880ad1
Create Date: 2026-08-21 15:32:29.367537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0eca8ed4f6e'
down_revision: Union[str, Sequence[str], None] = '674a00880ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_goals',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('goal_type', sa.String(length=40), nullable=False),
    sa.Column('target_weight_kg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('target_rate_kg_per_week', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('target_date IS NULL OR target_date >= start_date', name='ck_nutrition_goals_target_date_after_start'),
    sa.CheckConstraint('target_rate_kg_per_week IS NULL OR target_rate_kg_per_week > 0', name='ck_nutrition_goals_target_rate_positive'),
    sa.CheckConstraint('target_weight_kg IS NULL OR target_weight_kg > 0', name='ck_nutrition_goals_target_weight_positive'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nutrition_goals_person_status', 'nutrition_goals', ['person_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nutrition_goals_person_status', table_name='nutrition_goals')
    op.drop_table('nutrition_goals')
    # ### end Alembic commands ###
